### ISSUE TITLE
txt执行完py程序是不是就可以删了

### ISSUE THREAD

**Issue by ghost** [kallydev/privacy#12]
txt执行完py程序是不是就可以删了，小鸡空间太小，导入完数据库根目录的是不是就可以删掉了

**Comment by kallydev** [comment]
可以，只有最后生成的 database.db 有用。

**Comment by ghost** [comment]
> 可以，只有最后生成的 database.db 有用。

好的

**Comment by ghost** [comment]
<img width="487" alt="微信截图_20201130180743" src="https://user-images.githubusercontent.com/37090830/100596349-07158200-3337-11eb-85a1-2176ce675fdb.png">
这一步请问是在根目录执行还是在database目录执行

**Comment by Everless321** [comment]
你database.db的目录下执行

**Comment by ghost** [comment]
> 你database.db的目录下执行

这一步在昨天尝试的时候执行了半天没反应 请问这一步需要等待很长时间吗 先导入数据再执行这一步是吗？

**Comment by kallydev** [comment]
> 这一步请问是在根目录执行还是在database目录执行

执行 sqlite3 命令前，先 cd 到database.db 所在的目录。在出现的 Shell 里，依次执行这些 SQL 语句就行。

**Comment by ghost** [comment]
> > 这一步请问是在根目录执行还是在database目录执行
> 
> 执行 sqlite3 命令前，先 cd 到database.db 所在的目录。在出现的 Shell 里，依次执行这些 SQL 语句就行。

明白你说的意思 先执行py程序导入数据再执行这一步是吗？

**Comment by kallydev** [comment]
> 这一步在昨天尝试的时候执行了半天没反应 请问这一步需要等待很长时间吗 先导入数据再执行这一步是吗？

这种量级的数据创建索引比较耗时间。我在我自己的 SSD 上用 DataGrip 创建一个单列索引大致耗时 16 分钟。

**Comment by kallydev** [comment]
> 明白你说的意思 先执行py程序导入数据再执行这一步是吗？

是的，先通过脚本导入数据到 database.db 里。

**Comment by 77208149** [comment]
> txt执行完py程序是不是就可以删了，小鸡空间太小，导入完数据库根目录的是不是就可以删掉了
