### ISSUE TITLE
后端加载配置文件失败

### ISSUE THREAD

**Issue by creazytom** [kallydev/privacy#7]
[root@1 server]# ./app --config config.yaml
2020/11/29 02:12:37 failed to load config file
panic: failed to load config file

goroutine 1 [running]:
log.Panicln(0xc0000dbf08, 0x1, 0x1)
        /usr/lib/golang/src/log/log.go:352 +0xac
github.com/kallydev/privacy/service.NewService(0x7fff0890b328, 0xb, 0x0)
        /www/wwwroot/bgirl.ml/privacy/server/service/service.go:26 +0x105
main.main()
        /www/wwwroot/bgirl.ml/privacy/server/main/main.go:17 +0x3d

**Comment by southcat** [comment]
配置文件放到server目录下面

**Comment by creazytom** [comment]
老哥，还有一个问题就是怎么把结果里面的*去掉，正常显示信息

**Comment by kallydev** [comment]
> 老哥，还有一个问题就是怎么把结果里面的*去掉，正常显示信息

在 config.yaml 内把 mask 设置为 false，然后重启后端。

**Comment by creazytom** [comment]
好的谢谢

**Comment by creazytom** [comment]
> > 老哥，还有一个问题就是怎么把结果里面的*去掉，正常显示信息
> 
> 在 config.yaml 内把 mask 设置为 false，然后重启后端。

好的谢谢
