### ISSUE TITLE
前端查询的时候报错

### ISSUE THREAD

**Issue by Everless321** [kallydev/privacy#8]
查询自己qq报错unknown error
查询1的时候反而未查询到任何结果

**Comment by kallydev** [comment]
方便提供网址么，Telegram @kallydev

**Comment by Everless321** [comment]
http://199.195.252.22:8090/   我再重新导入下数据库   只导入一个qq库的话可以正常进行查询吗

**Comment by kallydev** [comment]
可以，你得在 config.yaml 内，把其他数据表都 false 掉。

**Comment by Everless321** [comment]
我false掉其他数据试一下

**Comment by Everless321** [comment]
还有个问题 生成索引的时候会占用主硬盘空间，怎么让他不占用主硬盘空间    ，主硬盘大小实在不够用

**Comment by kallydev** [comment]
> 还有个问题 生成索引的时候会占用主硬盘空间，怎么让他不占用主硬盘空间    ，主硬盘大小实在不够用

有一种方案叫`外置索引`，但是 SQLite 并不支持。我建议把 db 文件移动到其他硬盘，然后在 config.yaml 内修改 database 的 path 值。

**Comment by Everless321** [comment]
现在db文件就在挂载的硬盘上，但是生成索引的时候主硬盘空间占用一直在上升，最后提示空间不足生成索引失败

**Comment by kallydev** [comment]
> 现在db文件就在挂载的硬盘上，但是生成索引的时候主硬盘空间占用一直在上升，最后提示空间不足生成索引失败

```sql
PRAGMA temp_store_directory = '用于创建临时存储的目录';
```
